
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASIGN ELSE ID IF LBRACE LPAREN NUM OP_MUL OP_REL OP_SUMA PRINT RBRACE RPAREN SEMICOLON TIPO TIPO WHILEPrograma : SentenciasSentencias : Sentencia\n| Sentencias SentenciaSentencia : Declaracion\n| Asignacion\n| EstructuraControl\n| SentenciaPrintDeclaracion : TIPO ID SEMICOLONAsignacion : ID ASIGN Expresion SEMICOLONEstructuraControl : IF LPAREN Expresion RPAREN LBRACE Sentencias RBRACEEstructuraControl : IF LPAREN Expresion RPAREN LBRACE Sentencias RBRACE ELSE LBRACE Sentencias RBRACEEstructuraControl : WHILE LPAREN Expresion RPAREN LBRACE Sentencias RBRACESentenciaPrint : PRINT ID SEMICOLONExpresion : Termino\n| Expresion OP_SUMA Termino\n| Expresion OP_REL TerminoTermino : Factor\n| Termino OP_MUL FactorFactor : ID\n| NUM\n| LPAREN Expresion RPAREN'
    
_lr_action_items = {'TIPO':([0,2,3,4,5,6,7,13,19,28,29,40,41,42,43,44,45,47,48,49,],[8,8,-2,-4,-5,-6,-7,-3,-8,-13,-9,8,8,8,8,-10,-12,8,8,-11,]),'ID':([0,2,3,4,5,6,7,8,12,13,15,16,17,19,25,28,29,30,31,32,40,41,42,43,44,45,47,48,49,],[9,9,-2,-4,-5,-6,-7,14,18,-3,20,20,20,-8,20,-13,-9,20,20,20,9,9,9,9,-10,-12,9,9,-11,]),'IF':([0,2,3,4,5,6,7,13,19,28,29,40,41,42,43,44,45,47,48,49,],[10,10,-2,-4,-5,-6,-7,-3,-8,-13,-9,10,10,10,10,-10,-12,10,10,-11,]),'WHILE':([0,2,3,4,5,6,7,13,19,28,29,40,41,42,43,44,45,47,48,49,],[11,11,-2,-4,-5,-6,-7,-3,-8,-13,-9,11,11,11,11,-10,-12,11,11,-11,]),'PRINT':([0,2,3,4,5,6,7,13,19,28,29,40,41,42,43,44,45,47,48,49,],[12,12,-2,-4,-5,-6,-7,-3,-8,-13,-9,12,12,12,12,-10,-12,12,12,-11,]),'$end':([1,2,3,4,5,6,7,13,19,28,29,44,45,49,],[0,-1,-2,-4,-5,-6,-7,-3,-8,-13,-9,-10,-12,-11,]),'RBRACE':([3,4,5,6,7,13,19,28,29,42,43,44,45,48,49,],[-2,-4,-5,-6,-7,-3,-8,-13,-9,44,45,-10,-12,49,-11,]),'ASIGN':([9,],[15,]),'LPAREN':([10,11,15,16,17,25,30,31,32,],[16,17,25,25,25,25,25,25,25,]),'SEMICOLON':([14,18,20,21,22,23,24,36,37,38,39,],[19,28,-19,29,-14,-17,-20,-15,-16,-18,-21,]),'NUM':([15,16,17,25,30,31,32,],[24,24,24,24,24,24,24,]),'OP_MUL':([20,22,23,24,36,37,38,39,],[-19,32,-17,-20,32,32,-18,-21,]),'OP_SUMA':([20,21,22,23,24,26,27,33,36,37,38,39,],[-19,30,-14,-17,-20,30,30,30,-15,-16,-18,-21,]),'OP_REL':([20,21,22,23,24,26,27,33,36,37,38,39,],[-19,31,-14,-17,-20,31,31,31,-15,-16,-18,-21,]),'RPAREN':([20,22,23,24,26,27,33,36,37,38,39,],[-19,-14,-17,-20,34,35,39,-15,-16,-18,-21,]),'LBRACE':([34,35,46,],[40,41,47,]),'ELSE':([44,],[46,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Programa':([0,],[1,]),'Sentencias':([0,40,41,47,],[2,42,43,48,]),'Sentencia':([0,2,40,41,42,43,47,48,],[3,13,3,3,13,13,3,13,]),'Declaracion':([0,2,40,41,42,43,47,48,],[4,4,4,4,4,4,4,4,]),'Asignacion':([0,2,40,41,42,43,47,48,],[5,5,5,5,5,5,5,5,]),'EstructuraControl':([0,2,40,41,42,43,47,48,],[6,6,6,6,6,6,6,6,]),'SentenciaPrint':([0,2,40,41,42,43,47,48,],[7,7,7,7,7,7,7,7,]),'Expresion':([15,16,17,25,],[21,26,27,33,]),'Termino':([15,16,17,25,30,31,],[22,22,22,22,36,37,]),'Factor':([15,16,17,25,30,31,32,],[23,23,23,23,23,23,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Programa","S'",1,None,None,None),
  ('Programa -> Sentencias','Programa',1,'p_Programa','parser_ply.py',8),
  ('Sentencias -> Sentencia','Sentencias',1,'p_Sentencias','parser_ply.py',12),
  ('Sentencias -> Sentencias Sentencia','Sentencias',2,'p_Sentencias','parser_ply.py',13),
  ('Sentencia -> Declaracion','Sentencia',1,'p_Sentencia','parser_ply.py',17),
  ('Sentencia -> Asignacion','Sentencia',1,'p_Sentencia','parser_ply.py',18),
  ('Sentencia -> EstructuraControl','Sentencia',1,'p_Sentencia','parser_ply.py',19),
  ('Sentencia -> SentenciaPrint','Sentencia',1,'p_Sentencia','parser_ply.py',20),
  ('Declaracion -> TIPO ID SEMICOLON','Declaracion',3,'p_Declaracion','parser_ply.py',24),
  ('Asignacion -> ID ASIGN Expresion SEMICOLON','Asignacion',4,'p_Asignacion','parser_ply.py',28),
  ('EstructuraControl -> IF LPAREN Expresion RPAREN LBRACE Sentencias RBRACE','EstructuraControl',7,'p_EstructuraControl_if','parser_ply.py',32),
  ('EstructuraControl -> IF LPAREN Expresion RPAREN LBRACE Sentencias RBRACE ELSE LBRACE Sentencias RBRACE','EstructuraControl',11,'p_EstructuraControl_ifelse','parser_ply.py',36),
  ('EstructuraControl -> WHILE LPAREN Expresion RPAREN LBRACE Sentencias RBRACE','EstructuraControl',7,'p_EstructuraControl_while','parser_ply.py',40),
  ('SentenciaPrint -> PRINT ID SEMICOLON','SentenciaPrint',3,'p_SentenciaPrint','parser_ply.py',44),
  ('Expresion -> Termino','Expresion',1,'p_Expresion','parser_ply.py',48),
  ('Expresion -> Expresion OP_SUMA Termino','Expresion',3,'p_Expresion','parser_ply.py',49),
  ('Expresion -> Expresion OP_REL Termino','Expresion',3,'p_Expresion','parser_ply.py',50),
  ('Termino -> Factor','Termino',1,'p_Termino','parser_ply.py',54),
  ('Termino -> Termino OP_MUL Factor','Termino',3,'p_Termino','parser_ply.py',55),
  ('Factor -> ID','Factor',1,'p_Factor','parser_ply.py',59),
  ('Factor -> NUM','Factor',1,'p_Factor','parser_ply.py',60),
  ('Factor -> LPAREN Expresion RPAREN','Factor',3,'p_Factor','parser_ply.py',61),
]
